### ISSUE TITLE
nginx conf file example

### ISSUE THREAD

**Issue by ma7555** [s-nomp/s-nomp#103]
I am having hard time figuring out how to host the pool using nginx. requesting an example of the conf file when pool config has the following settings:  (and whether it could be hosted when enabled set to false and only rely on nginx)

```
["website": {
        "enabled": true,
        "host": "xx.xx.xx.xx",
        "port": 8080,
        "stratumHost": "127.0.0.1",
```

I am trying to setup basic username and password authentication for solo pool

Regards,
ma7555

**Comment by zzzpotato** [comment]
I use the following. `stratumHost` is shown in your "getting started" page so you can set it to a server hostname or ip address to display. 

Simply change YOURDOMAIN and _SERVERIP_

Others may have better examples. For https I just use cloudflare.

```
server {
    listen 80;
    server_name YOURDOMAIN;
    location / {

     if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET';
        add_header 'Access-Control-Allow-Headers' 'Content-Type';
        #add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
     }

        proxy_pass http://SERVERIP:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
     }
}
```

**Comment by ma7555** [comment]
thanks for sharing, I would suggest adding it to the git repo as an example for nginx.

edit: sorry just found out it has been already there for 10 months.
