### ISSUE TITLE
 npm start ERR

### ISSUE THREAD

**Issue by zhq1** [s-nomp/s-nomp#105]
root@pool:~/s-nomp# npm start

> s-nomp@0.0.9 start /root/s-nomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

/root/s-nomp/node_modules/bindings/bindings.js:91
        throw e
        ^

Error: The module '/root/s-nomp/node_modules/equihashverify/build/Release/equihashverify.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 67. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/root/s-nomp/node_modules/bindings/bindings.js:84:48)
    at Object.<anonymous> (/root/s-nomp/node_modules/equihashverify/index.js:1:99)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! s-nomp@0.0.9 start: `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s-nomp@0.0.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-24T14_56_33_205Z-debug.log

root@pool:~/s-nomp# node -v
v8.11.4

**Comment by zhq1** [comment]
root@pool:~/s-nomp# nvm ls
->      v8.11.4
         system
default -> 8.11 (-> v8.11.4)
node -> stable (-> v8.11.4) (default)
stable -> 8.11 (-> v8.11.4) (default)
iojs -> N/A (default)
lts/* -> lts/dubnium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.15.1 (-> N/A)
lts/carbon -> v8.14.1 (-> N/A)
lts/dubnium -> v10.14.2 (-> N/A)

**Comment by mawenpeng** [comment]
Hi @zhq1,
Have you fixed this err? How do you fix it?

**Comment by mawenpeng** [comment]
I found the workaround, may need to downgrade to node v8.15.1: https://nodejs.org/dist/v8.15.1/
