### ISSUE TITLE
website died

### ISSUE THREAD

**Issue by BaikalMine** [s-nomp/s-nomp#108]
undefined:3
var out='<style>\n    #topCharts{\n        padding: 18px;\n    }\n    #topCharts > div > div > svg{\n        display: block;\n        height: 280px;\n    }\n    .chartWrapper{\n        border: solid 1px #c7c7c7;\n        border-radius: 5px;\n        padding: 5px;\n        margin-bottom: 18px;\n    }\n    .chartLabel{\n        font-size: 1.2em;\n        text-align: center;\n        padding: 4px;\n    }\n    .chartHolder{\n\n    }\n\n    #boxesLower {\n        margin: 0 9px;\n    }\n    #boxesLower > div {\n        display: flex;\n    }\n    #boxesLower > div > div {\n        flex: 1 1 auto;\n        margin: 0 9px 18px 9px;\n        padding: 10px;\n        display: flex;\n        flex-direction: column;\n    }\n    .boxLowerHeader{\n        font-size: 1.3em;\n        margin: 0 0 5px 10px;\n    }\n    #boxStatsLeft{\n        color: black;\n        background-color: #cccccc;\n    }\n    #boxStatsRight{\n        color: black;\n        background-color: #cccccc;\n    }\n    .boxStats{\n        color:

TypeError: Cannot read property 'split' of undefined
    at Object.eval [as stats] (eval at doT.template (/work/s-nomp/node_modules/dot/doT.js:133:11), <anonymous>:3:7102)
    at processTemplates (/work/s-nomp/libs/website.js:61:62)
    at /work/s-nomp/libs/website.js:93:13
    at /work/s-nomp/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/work/s-nomp/node_modules/async/dist/async.js:1064:13)
    at /work/s-nomp/node_modules/async/dist/async.js:969:16
    at /work/s-nomp/libs/website.js:86:17
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

**Comment by egyptianbman** [comment]
Closing since this doesn't have any information about the environment. Please don't use github for support. Join the Discord group and ask for help there first.
