### ISSUE TITLE
equihash n=150, k=5 beam

### ISSUE THREAD

**Issue by goodthebest** [s-nomp/s-nomp#110]
hey Devs, 

I want to mine Beam coin  but they are using equihash parameters n=150, k=5. Can s-nomp work with it? I couldn't find coin name in the coins folder?

**Comment by egyptianbman** [comment]
BEAM isn't a zcash fork so isn't compatible with s-nomp by default. Feel free to contact the BEAM devs and ask them to provide a pull request adding support, allowing all the s-nomp pools to add their coin; thanks!
