### ISSUE TITLE
Invalid solution: invalid collision length between StepRows

### ISSUE THREAD

**Issue by jeromemorignot** [s-nomp/s-nomp#114]
Hi,

I just configured ZelCash, and for every share I get that type of error:
Invalid solution: invalid collision length between StepRows
X[i]   = fa43261ac3243d31986370533c7c2c2084c9
X[i+1] = bc9bfe18ccab3d0b8a568f1fd9c098f147bd

My coins config is the latest one. And the pool config is the following:
 "ports": {
                        "1234": {
            "tls": false,
            "diff": 0.2,
            "varDiff": {
                "minDiff": 0.001,
                "maxDiff": 4096,
                "targetTime": 5,
                "retargetTime": 5,
                "variancePercent": 30
            }

I get this running a simple GPU mining rig.

Thank you!

**Comment by jeromemorignot** [comment]
Just needed to update the equihashverify

**Comment by wangjianbao** [comment]
@jeromemorignot  I have the same question, and you have solved it?
