### ISSUE TITLE
ZEN is not mined after hardfork

### ISSUE THREAD

**Issue by iRespectrum** [s-nomp/s-nomp#12]
We thought a block was found but it was rejected by the daemon, share data: {"job":"ccee","ip":"::ffff:159.8.13.230","port":4004,"worker":"znUA2dRUmJJEehdeW4C7FyxEakUe3rcwM6v.noname","height":345238,"difficulty":32,"shareDiff":"3153402.56727047","blockDiff":1552038.25889263,"blockDiffActual":1552038.25889263,"blockHash":"000000002a90156e82cd3da578b82afa5fb2e5d8aebcbe2fb2a5d51301430284","error":{"unknown":"check coin daemon logs"}}

And so 10 blocks in a row. I lost a lot of coins

**Comment by Gumbees** [comment]
What did ZEN change during the hard fork? Not many of us have many miners in ZEN.

**Comment by iRespectrum** [comment]
in the coin / zen.json need to make changes?
The award is now for the block of 70%

**Comment by Gumbees** [comment]
Try this.

EDIT: Not on 144,5 confirmed.

**Comment by egyptianbman** [comment]
Wait, is ZEN on 144,5?

**Comment by egyptianbman** [comment]
@iRespectrum can you provide the output of the daemon logs?

**Comment by Gumbees** [comment]
@egyptianbman https://blog.zencash.com/zencash-statement-on-potential-equihash-algorithm-change/

**Comment by iRespectrum** [comment]
@egyptianbman I run zencash with -printtoconsole

**Comment by Gumbees** [comment]
@iRespectrum They're not on 144,5. So don't use my snippet. Looks like it has to do w/ Supernodes. Maybe overwinter.. but not 100% yet. 

But it looks like we're behind w/ ZenCash's commits.

**Comment by egyptianbman** [comment]
@iRespectrum you should still have the output somewhere. Either way, it looks like they've implemented supernodes in their own stratum-pool. We'll port these but it's not a "5 minute thing" as we'll need to test the changes. You can switch your zen pool to use their stratum-pool -- https://github.com/ZencashOfficial/node-stratum-pool

**Comment by iRespectrum** [comment]
@egyptianbman then wait for the new coin configuration

**Comment by nettts** [comment]
@
