### ISSUE TITLE
Zhash / ZEL not working with NH

### ISSUE THREAD

**Issue by ma7555** [s-nomp/s-nomp#120]
Authentication happens, 
2019-02-25 22:45:26 [Pool]  [zelcash] (Thread 1) Authorized XXXXXXXXXX:c=ZEL [::ffff:169.45.82.248]

No workers are getting assigned though.. I have tried other pools, some are working and some are not.
Specs shared on NH: https://github.com/nicehash/Specifications/blob/master/Zhash_NiceHash_v1.0.txt
Any ideas?

**Comment by egyptianbman** [comment]
@ma7555 I don't plan to add NH support to s-nomp. Coins that fork away from 200,9 do so to remain asic and nicehash resistant. As pools, we should respect their wishes and help them in this endeavor.

**Comment by ma7555** [comment]
understood thanks pal
