### ISSUE TITLE
Unauthorized messages when trying to connect to Pirate

### ISSUE THREAD

**Issue by newvulcan** [s-nomp/s-nomp#123]
I am trying to set up Pirate with S-Nomp, but I am getting the following error message:

2019-03-26 14:23:40 [Pool]      [pirate] (Thread 1) Unauthorized  zs1xxx

As Pirate has to have privateChain set to true in pirate.json in /s-nomp/coins is S-Nomp compatible with this particular coin ? I have sapling set to true in the coin json file.

**Comment by zzzpotato** [comment]
S-nomp does not support pirate currently because it is not setup to use Z to Z transactions
