### ISSUE TITLE
Switching call by CLI broken

### ISSUE THREAD

**Issue by jeromemorignot** [s-nomp/s-nomp#125]
Hi,

I enabled a switch port on my pool, individual coins works perfectly. But when I can the cli command to switch, I get this : 
/root/s-nomp/node_modules/stratum-pool/lib/pool.js:731
                clientsToRelinquish.forEach(function(cObj) {
                                    ^

TypeError: Cannot read property 'forEach' of null
    at /root/s-nomp/node_modules/stratum-pool/lib/pool.js:731:37
    at /root/s-nomp/node_modules/async/dist/async.js:3377:9
    at /root/s-nomp/node_modules/async/dist/async.js:473:16
    at eachOfArrayLike (/root/s-nomp/node_modules/async/dist/async.js:1057:9)
    at eachOf (/root/s-nomp/node_modules/async/dist/async.js:1117:5)
    at filterArray (/root/s-nomp/node_modules/async/dist/async.js:3366:5)
    at _filter (/root/s-nomp/node_modules/async/dist/async.js:3407:5)
    at Object.<anonymous> (/root/s-nomp/node_modules/async/dist/async.js:1122:16)
    at pool.relinquishMiners (/root/s-nomp/node_modules/stratum-pool/lib/pool.js:727:15)
    at process.<anonymous> (/root/s-nomp/libs/poolWorker.js:73:29)
---------

Cli command is : 
node /root/s-nomp/scripts/cli.js coinswitch horizen Equihash

---
My config related to switching is:
   "switching": {
        "Equihash": {
            "enabled": true,
            "algorithm": "equihash",
            "ports": {
                "3333": {
                    "diff": 32768
                }
            }
        }
    }

Thank you!

**Comment by jeromemorignot** [comment]
I fixed the issue by applying this fix from UNOMP
https://github.com/UNOMP/unified-node-open-mining-portal/issues/95#issuecomment-204865124

**Comment by DeckerSU** [comment]
Faced with the same problem today:
```
clientsToRelinquish.forEach(function (cObj) {
TypeError: Cannot read property 'forEach' of null
```
Solved it by two changes (without crutches):
- in `node-stratum-pool/lib/pool.js`: https://github.com/DeckerSU/node-stratum-pool/commit/d3dafec02cc566366c5bb043c115f0527eacd7fc#diff-bbb580747701b731142b6584ae61643bR654
- in `libs/poolWorker.js`: https://github.com/DeckerSU/z-nomp/commit/4845c3e471ddf1c5616e2f0617841153cea7db99#diff-d74b89e1c96aa6ced7a4b07175d023aeR77
I guess this solution is applicable and for s-nomp too.
