### ISSUE TITLE
Pending block for more than a day

### ISSUE THREAD

**Issue by goodthebest** [s-nomp/s-nomp#126]

**Comment by zzzpotato** [comment]
Send a small amount of ZEC to the second T address in your config to cover the initial tx fees (~0.001 ZEC). Less will probably work too.

**Comment by goodthebest** [comment]
@zzzpotato thanks for your prompt response. Did you mean wallet's lacking in tx fees, that's why reward is stuck? I'm little confused.

**Comment by zzzpotato** [comment]
Yes, it needs a small initial amount of funding in the pools wallet to process.

**Comment by goodthebest** [comment]
Another question to clarify, in **zec.json**, should small amount  be sent to first mining address "address": or "tAddress": or "invalidAddress" ? or any t address on the same wallet?

**Comment by zzzpotato** [comment]
https://github.com/s-nomp/s-nomp/blob/master/pool_configs/examples/zec.json#L11

**Comment by goodthebest** [comment]
I've sent a small balance of 0.01 to this circled address but still reward is stuck. I've attached you original zec.json file used for the pool

![image](https://user-images.githubusercontent.com/1715740/55981441-bce61580-5ca7-11e9-9bcc-5a68e5777f30.png)

**Comment by zzzpotato** [comment]
It will need 10 confirmations I think to see the funds you just sent

**Comment by goodthebest** [comment]
It's not the case I figured out, pool reward went to private balance to z account

**Comment by goodthebest** [comment]
Thanks it helped.
