### ISSUE TITLE
Komodo and Piratechain mining

### ISSUE THREAD

**Issue by Poolmin** [s-nomp/s-nomp#131]
Hello I try to setup pool for piratechain mining but when I try to mine i get block fail with that error in coin debug.log file:

CheckBlockHeader komodo_check_deposit error
ERROR: ProcessNewBlock: CheckBlock FAILED

There's something wrong in my coin/pool setup or s-nomp is simply not compatible with piratechain and komodo coin ?

**Comment by zzzpotato** [comment]
s-nomp does not support z-to-z transactions required by pirate. kmd should work unless they've made some major changes recently. we'll need more info to troubleshoot komodo
