### ISSUE TITLE
Website launch problem

### ISSUE THREAD

**Issue by aowei020** [s-nomp/s-nomp#135]
What should config.json fill in here, if left blank, affect the operation of the website? 
"poolHex": ", 

In addition, I prompted for an error when I started the site: 

2019-05-22 10:27:44 [Pool] [zcash] (Thread 1) Error with getblocktemplate on creating first job, server cannot start. 

How should we solve it?

**Comment by egyptianbman** [comment]
If you leave it blank, the default is used. You can search the code for `poolHex` to find where it's used: https://github.com/search?q=org%3As-nomp+poolHex&type=Code

If the pool can't get the block template from the node, it can't let people mine. Make sure your connection is correct and that the node is fully synced.
