### ISSUE TITLE
ARW pool  was  stopped   http://52.90.76.26/stats

### ISSUE THREAD

**Issue by Stargazer77** [s-nomp/s-nomp#158]
ARW pool  was  stopped! http://52.90.76.26/stats
What wrong?

**Comment by Stargazer77** [comment]
I worked about 10 hours idle.

**Comment by zzzpotato** [comment]
You'll need to be more specific. Do you mean the pending blocks are stuck from being paid? Restart your pool and it should start the payment processor again.

**Comment by Stargazer77** [comment]
I am just a working miner. This is not my pool. I don’t know who to turn to for support. he was just stuck on but for some reason he  gave shares and took them but the statistics are not updated. Will I get my coins as a result?

**Comment by zzzpotato** [comment]
You'll need to get in contact with the pool operator for assistance. Nobody would be able to answer that other than them :(
