### ISSUE TITLE
Miners connected to pool 10 or so minutes then pool shows 0 Miners but miner connected. 

### ISSUE THREAD

**Issue by bps1980** [s-nomp/s-nomp#160]
I reset miners and it eventually repeats itself. Why pool shows 0 miners, how can I fix this?

![Screenshot from 2019-12-12 19-12-14](https://user-images.githubusercontent.com/43716655/70761636-77d12200-1d13-11ea-85e3-32e75fde44f8.png)
![Screenshot from 2019-12-12 19-12-21](https://user-images.githubusercontent.com/43716655/70761641-7c95d600-1d13-11ea-8fe3-070a55e9ccda.png)

**Comment by zzzpotato** [comment]
I see half your shares are discarded and half accepted (if i'm reading this right). Hashrate seems to show the same with up and down movement from 0 to 68k sol/s. You should watch your pools console to see if you are getting a lot of rejected shares suddenly. My guess would be overclocking is too high. Too many rejected shares might be banning you from the pool for a short bit.

**Comment by egyptianbman** [comment]
Closing issue due to no response.
