### ISSUE TITLE
Bsha3 mining is off completely

### ISSUE THREAD

**Issue by Z1ldj1an** [s-nomp/s-nomp#161]
Bsha3 mining is off completely.
Hashrate shown and calculated in Ksol/s, as a result Luck jumps to tens of thousands of days.

The quantity of shares changes but to no avail. By the data shown - I have not mined anything in 24h, which is frakly wrong. 

Also the maturisation of the coin is not happening at this moment. I've been mining for over 24h and received none.

**Comment by egyptianbman** [comment]
Bsha3 isn't equihash.

**Comment by Z1ldj1an** [comment]
I know!
That's why I opened the ticket!

It shows bonkers!

**Comment by Z1ldj1an** [comment]
And the calculations are wrong + payout is stuck!

**Comment by Z1ldj1an** [comment]
![Screenshot_2020-01-19-11-01-38-977_org chromium chrome](https://user-images.githubusercontent.com/59488738/72680197-e007e600-3abf-11ea-90da-17a55feb8abd.jpg)
![Screenshot_2020-01-19-11-00-29-081_org chromium chrome](https://user-images.githubusercontent.com/59488738/72680198-e007e600-3abf-11ea-88f5-992e63fd1d8e.jpg)
![Screenshot_2020-01-19-11-01-26-347_org chromium chrome](https://user-images.githubusercontent.com/59488738/72680199-e007e600-3abf-11ea-8355-8354abbb50ce.jpg)

**Comment by egyptianbman** [comment]
s-nomp only supports equihash at this time.

**Comment by Z1ldj1an** [comment]
Why is it marked BSHA3 then?

Where did it go? Will it be supported?

**Comment by Z1ldj1an** [comment]
What about my coins left on the pool?

I had ~140 bsha3 left to mature..

**Comment by egyptianbman** [comment]
Please know that this repository is for s-nomp. We have no affiliation with pow-coin.com. They are running s-nomp, but that's all. There is no help anyone here can provide you with relation to your mining on pow-coin.com.

**Comment by Z1ldj1an** [comment]
Ooh.. OK.
You could have stated that from the very beginning dear.

Thank you for your help!

Good day to you!
