### ISSUE TITLE
need help no blocks after 2 days

### ISSUE THREAD

**Issue by 49handyman** [s-nomp/s-nomp#175]
running 4 x z9 no blocks found.

i find 3-5 blocks on solopool every day.

looks like it works

but no blocks
![shares](https://user-images.githubusercontent.com/14155275/108410838-848db780-71ed-11eb-902d-e40a974c36d1.PNG)
![bitcoinz](https://user-images.githubusercontent.com/14155275/108410923-a0915900-71ed-11eb-8f84-089a6820dfe9.PNG)
![solo1](https://user-images.githubusercontent.com/14155275/108410993-b737b000-71ed-11eb-9ba4-285ae75b77b8.PNG)
![s-nomp3](https://user-images.githubusercontent.com/14155275/108411120-ddf5e680-71ed-11eb-946b-e7724555de86.PNG)

**Comment by zzzpotato** [comment]
Please use k-nomp
