### ISSUE TITLE
any idea why I get this...trying to start??

### ISSUE THREAD

**Issue by interbiznw** [s-nomp/s-nomp#180]
![image](https://user-images.githubusercontent.com/16450422/148671173-caa51617-d8e3-4e79-97a5-3ded6c989898.png)

**Comment by cryptooliko** [comment]
https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6

**Comment by interbiznw** [comment]
> [Marak/colors.js@074a0f8](https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6)

oh.. Well what about the screwed output? It wont run, and lags super bad on any machine I try to run it on?

**Comment by interbiznw** [comment]
Nevermind I didnt get what you meant at first, Now i see the news about him sabotaging the repo

**Comment by zzzpotato** [comment]
Try replacing this line with the following
https://github.com/s-nomp/s-nomp/blob/master/package.json#L39

`"colors": "git+https://github.com/DABH/colors.js.git"`
