### ISSUE TITLE
GLINK block reward 

### ISSUE THREAD

**Issue by minershaven** [s-nomp/s-nomp#198]
We are having an issue of not receiving the full block reward on our pool.  Block reward should be 9 but all we ever seem to receive is 2.8. Link to our latest block is  https://explorer.gemlink.org/block/000005a48c4de895db2e764ac7fd220494a090b32f58e4b9c49a752810e13a39

Our pool wallet is the one getting 2.8 then the 15 and 6 payments to the masternodes and devs and the other 2 wallets listed are pool fee wallets.  Is there anything in the coin or pool config files that would cause this?

**Comment by minershaven** [comment]
Here is a screenshot of our blocks mined and coins paid. All blocks have been paid out and we don't show any pending balances to miners. The coin amount should be much higher. 

![Screenshot_20220929_183646_Chrome](https://user-images.githubusercontent.com/57435138/193160467-a2873ced-4f7f-4a88-83cb-a547ac9ea524.jpg)

**Comment by zzzpotato** [comment]
Can you post the rewardRecipients from your pool_config?

```
    "rewardRecipients": {
        "": 0.2
    },
```
