### ISSUE TITLE
Official Zen Explorer

### ISSUE THREAD

**Issue by tarrenj** [s-nomp/s-nomp#20]
https://github.com/z-nomp/z-nomp/blob/4b9401d88dbb0c0b67b4d7f6e047e6fdb53b0513/coins/zen.json#L73

The official Zen explorer is https://explorer.zensystem.io/  The zen-solutions one is run by a community member.  Is there an easy way to add two explorers?

**Comment by Gumbees** [comment]
It's possible, but we'd need to find a nice way of proposing the lookup to the user. Currently it just links the block to the explorer directly.

Should we update this to the official explorer?

**Comment by tarrenj** [comment]
Using the official one is preferred. I'll submit a PR now.

**Comment by sennevb** [comment]
@tarrenj People tend to use the other one because zen's official explorer doesnt show the block finder

**Comment by Gumbees** [comment]
I'll make a final decision tomorrow on whether to close or merge this request. Thank you all.

**Comment by Gumbees** [comment]
@tarrenj @sennevb I agree the official coin explorers should be used by default unless there isn't one available. The end user can change this if the official coin explorer isn't satisfactory. 

I will be approving the pull request.

For future reference, pull requests for official explorers for coins that we have not updated will be approved.

**Comment by tarrenj** [comment]
Thanks!  I reread my above comment and i didn't mean to make it sound so official.  It's your call if you'd rather use the zen-solutions one.

**Comment by sennevb** [comment]
@tarrenj why Does official one don't include block finders (Pools) ?

**Comment by tarrenj** [comment]
@sennevb I'm not actually sure. We'll likely be making this the new "official" pool software for Zen shortly.
