### ISSUE TITLE
zen -tAddress

### ISSUE THREAD

**Issue by goodthebest** [s-nomp/s-nomp#200]
hey @zzzpotato devs, I'm trying to setup zen pool, everything seems fine with the setup however when generating tAddress using **zen-cli getnewaddress** it generates an address starting from **z**. when running the pool, it gives this error. any clue?

Shouldn't it generate an address starting from **t**?
`zen-cli getnewaddress`
`znafw4TVy7vcSgqJvSpN6WiWhBbtfrNTjUE`

`zen-cli z_getnewaddress`
`zcBPoL2MG3UMVCog1YBqcZtGmUokUoGUdSA2tZ3dKj1SDhj5RQef75qxURRwjHodAMZ4adF9aHsqwztgasn2TKZ5SsGUuEu`

![image](https://user-images.githubusercontent.com/1715740/201483390-e149a113-33d8-48db-a7e8-89304bab502e.png)

**Comment by minershaven** [comment]
T addresses with Zen also start with z.  Z addresses are just much longer but both will start with a z.  For more details see
https://github.com/HorizenOfficial/zen/wiki/1.0-User-Guide#generating-a-t-addr

**Comment by goodthebest** [comment]
but s-nomp is't recognizing that taddress starting from **z**? I've put out a screenshot above.

**Comment by xt18** [comment]
> but s-nomp is't recognizing that taddress starting from **z**? I've put out a screenshot above.

Your pool config is incorrect, I checked mine and its working fine with Taddress starting with z. The error indicates your wallet does not own the addresses and its failing to start, make sure you are pointing to correct daemon.

**Comment by minershaven** [comment]
Use zen-cli getaddressesbyaccount "" and make sure that address shows up in the output. If not replace it with the address that does come up.

**Comment by goodthebest** [comment]
Thanks you guys, I had to delete .zen folder and sync'ed the blockchain anew and then generated addresses from the scratch, everything went smoothly.
