### ISSUE TITLE
ZEN blocks found but never confirmed

### ISSUE THREAD

**Issue by goodthebest** [s-nomp/s-nomp#201]
I'm using s-nomp repo, pool have found ZEN [Horizen] blocks but they are still pending after over 289 confirmations. Any clue?

![image](https://user-images.githubusercontent.com/1715740/202563921-d5527e83-13a9-4211-b2be-6d109b9d3230.png)

**Comment by zzzpotato** [comment]
Send a little ZEN to your payout address to cover the initial fee. 0.001
