### ISSUE TITLE
zen.json coin config file

### ISSUE THREAD

**Issue by tarrenj** [s-nomp/s-nomp#21]
The `zen.json` coin config file is not compatible with Zen, please update to be inline with the one here: https://github.com/zencashofficial/z-nomp/blob/master/coins/zen.json

Also, the testnet config file as well.

**Comment by egyptianbman** [comment]
Hey @tarrenj there's a PR for this: https://github.com/z-nomp/z-nomp/pull/17/files

**Comment by tarrenj** [comment]
Yep, just saw that after opening this issue.  Thanks!
