### ISSUE TITLE
Invalid solution: duplicate indices

### ISSUE THREAD

**Issue by Xandrah** [s-nomp/s-nomp#23]
Every miner that connects to my pool has this error, 
2018-07-31 20:38:10 [Pool]      [zclassic] (Thread 1) Share rejected: {"job":"cccf","ip":"::ffff:37.187.129.166","worker":"t1cPdya6ksXqPwco3gLSSZ4hmNeofwBZAt4.noname","difficulty":0.08928571,"error":"invalid solution"}
Invalid solution: duplicate indices

This is your latest repo.

**Comment by egyptianbman** [comment]
Did you ensure to update npm packages? Also, can you provide your configuration?

**Comment by Xandrah** [comment]
All npm packages are updated, which config do you want.

**Comment by egyptianbman** [comment]
Just to confirm your coin configs aren't modified.

Also, does the daemon logs show anything?

Can you confirm that `node_modules/stratum-pool/lib/transactions.js` matches https://github.com/z-nomp/node-stratum-pool/blob/master/lib/transactions.js?

**Comment by Xandrah** [comment]
It seems to be only one user doing this issue, I have tested mining myself and do not get any error messages, could the user be attacking the pool?

**Comment by egyptianbman** [comment]
More than likely it's bad overclocks. As long as their shares are being rejected, you're good. Closing this issue as it seems to be resolved.

**Comment by Jerry170617** [comment]
@Xandrah I have the same problem, how to solve it.
