### ISSUE TITLE
votecoin submit block error.

### ISSUE THREAD

**Issue by Xandrah** [s-nomp/s-nomp#24]
Z-NOMP

[32m2018-08-01 02:19:18 [Pool]	[39m[3m[votecoin] [23m[90m[1m(Thread 2) [22m[39m[90mSubmitted Block using submitblock successfully to daemon instance(s)[39m
[32m2018-08-01 02:19:18 [Pool]	[39m[3m[votecoin] [23m[90m[1m(Thread 2) [22m[39m[90mWe thought a block was found but it was rejected by the daemon, share data: {"job":"cd2f","ip":"::ffff:188.166.161.62","port":3039,"worker":"t1Lj2s6XSMhi4dcyLrD1sA8iizSus1FvU7r.lm2","height":194372,"difficulty":2.79352661,"shareDiff":"4411.71734849","blockDiff":3912.254875098,"blockDiffActual":3912.254875098,"blockHash":"00000076d702f731b749352c1d0892a839952ad0a056564425d00662cce5eb6e","error":{"unknown":"check coin daemon logs"}}[39m
[32m2018-08-01 02:19:27 [Payments]	[39m[3m[zen] [23m[90mFinished interval - time spent: 13ms total, 5ms redis, 6ms daemon RPC[39m

coin daemon

2018-08-01 02:19:18 ERROR: CheckBlock(): hashMerkleRoot mismatch
2018-08-01 02:19:18 ERROR: ProcessNewBlock: CheckBlock FAILED

**Comment by sennevb** [comment]
@Xandrah is fixed in latest bitcoinjs-lib change no? can be closed?

**Comment by Xandrah** [comment]
Resolved with hellcatz revert :) Please use git+https://github.com/z-nomp/bitcoinjs-lib#bug/restore-hellcatz-overwinter
