### ISSUE TITLE
Installed with errors, pool will not run

### ISSUE THREAD

**Issue by osheen2241** [s-nomp/s-nomp#33]
Installed the pool with dependencies but still get errors staring up. I've also install zclassic znomp without the same errors.  My main goal is to mine a overwinter block in the test net but it absolutely does not work with all implementations of znomp Ive tried. 

For reference I have zcash 1.1.0, 1.1.1, 1.1.2 installed. I am using 1.1.0 to test overwinter transaction. 

Keep up the good work, I've been  keeping an eye on this repository as it seems to be promising.  Hope my observations help. 

```
Error: Invalid checksum
    at Object.decode (/home/miningcore/Downloads/z-nomp/node_modules/bs58check/base.js:41:25)
    at Object.fromBase58Check (/home/miningcore/Downloads/z-nomp/node_modules/bitcoinjs-lib-zcash/src/address.js:11:27)
    at recipients.forEach.recipient (/home/miningcore/Downloads/z-nomp/node_modules/stratum-pool/lib/transactions.js:234:39)
    at Array.forEach (<anonymous>)
    at Object.exports.createGeneration (/home/miningcore/Downloads/z-nomp/node_modules/stratum-pool/lib/transactions.js:233:16)
    at new BlockTemplate (/home/miningcore/Downloads/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:58:35)
    at JobManager.processTemplate (/home/miningcore/Downloads/z-nomp/node_modules/stratum-pool/lib/jobManager.js:155:32)
    at /home/miningcore/Downloads/z-nomp/node_modules/stratum-pool/lib/pool.js:601:66
    at itemFinished (/home/miningcore/Downloads/z-nomp/node_modules/stratum-pool/lib/daemon.js:166:36)
    at /home/miningcore/Downloads/z-nomp/node_modules/stratum-pool/lib/daemon.js:180:17
2018-08-06 19:55:12 [Master]	[PoolSpawner] Fork 14 died, spawning replacement worker...
2018-08-06 19:55:13 [Switching]	[Setup] (Thread 7) Loading last proxy state from redis
2018-08-06 19:55:13 [Pool]	[zcash_testnet] (Thread 7) Share processing setup with redis (127.0.0.1:6379)
/home/miningcore/Downloads/z-nomp/node_modules/bs58check/base.js:41
    if (!payload) throw new Error('Invalid checksum')
                  ^
```

**Comment by egyptianbman** [comment]
Can you provide your configuration?

**Comment by Gumbees** [comment]
@osheen2241 Be aware that testnet for zcash will not function with this edition of z-nomp since Sapling is now on zcash testnet. We're hoping to support Sapling soon.

To your current issue, provide config as @egyptianbman asked. Thanks!

**Comment by osheen2241** [comment]
Sure,   
{
    "logLevel": "debug",
    "logColors": true,

    "cliPort": 17117,

    "clustering": {
        "enabled": true,
        "forks": "auto"
    },

    "defaultPoolConfigs": {
        "blockRefreshInterval": 500,
        "jobRebroadcastTimeout": 55,
        "connectionTimeout": 600,
        "emitInvalidBlockHashes": false,
        "validateWorkerUsername": true,
        "tcpProxyProtocol": false,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 500,
            "purgeInterval": 300
        },
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "password": ""
        }
    },

    "website": {
        "enabled": true,
        "host": "0.0.0.0",
        "port": 8080,
        "stratumHost": "cryppit.com",
        "stats": {
            "updateInterval": 30,
            "historicalRetention": 14400,
            "hashrateWindow": 300
        },
        "adminCenter": {
            "enabled": false,
            "password": "password"
        },
        "tlsOptions" : {
            "enabled": false,
            "cert": "",
            "key": ""
        }
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "switching": {
        "switch1": {
            "enabled": false,
            "algorithm": "sha256",
            "ports": {
                "3333": {
                    "diff": 10,
                    "varDiff": {
                        "minDiff": 16,
                        "maxDiff": 512,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            }
        },
        "switch2": {
            "enabled": false,
            "algorithm": "scrypt",
            "ports": {
                "4444": {
                    "diff": 10,
                    "varDiff": {
                        "minDiff": 16,
                        "maxDiff": 512,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            }
        },
        "switch3": {
            "enabled": false,
            "algorithm": "x11",
            "ports": {
                "5555": {
                    "diff": 0.001,
                    "varDiff": {
                        "minDiff": 0.001,
                        "maxDiff": 1,
                        "targetTime": 15,
                        "retargetTime": 60,
                        "variancePercent": 30
                    }
                }
            }
        }
    },

    "profitSwitch": {
        "enabled": false,
        "updateInterval": 600,
        "depth": 0.90,
        "usePoloniex": true,
        "useCryptsy": true,
        "useMintpal": true,
        "useBittrex": true
    }
}

Pool configuration, I removed daemon username and password and the zadd.  


{
    "enabled": true,
    "coin": "zec.json",

    "address": "tmDRtohUPp9QGrCW9NSzq9RcFBJW1sGybgu",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "tmDRtohUPp9QGrCW9NSzq9RcFBJW1sGybgu",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

    "invalidAddress":"",
    "_comment_invalidAddress": "Invalid addresses will be converted to the above",

    "walletInterval": 2.5,
    "_comment_walletInterval": "Used to cache coin stats",

    "rewardRecipients": {
        "": 0.2
    },

    "tlsOptions": {
        "enabled": false,
        "serverKey": "",
        "serverCert": "",
        "ca": ""
    },

    "paymentProcessing": {
        "enabled": true,
        "minConf": 10,
        "paymentMode": "prop",
        "_comment_paymentMode": "prop, pplnt",
        "paymentInterval": 120,
        "minimumPayment": 0.05,
        "maxBlocksPerPayment": 3,
        "daemon": {
            "host": "127.0.0.1",
            "port": 8232,
            "user": "",
            "password": ""
        }
    },

    "ports": {
        "3032": {
            "diff": 0.5,
            "tls": false,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 36,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "poolId": "main",
    "_comment_poolId": "use it for region identification: eu, us, asia or keep default if you have one stratum instance for one coin",

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 8232,
            "user": "",
            "password": ""
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "zec",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}

here you go @egyptianbman.  Also @nettts  Im using zcash daemon version 1.1.0 for the testnet. I guess its the only version with overwinter testnet. 

Thanks again!

**Comment by egyptianbman** [comment]
I'm seeing several things that are empty in your pool configuration -- addresses and hostnames, etc. This is actually the reason you're seeing the error. Please go through the configs and make sure anything that needs a value, has one.

**Comment by osheen2241** [comment]
I changed hostname to 0.0.0.0 , my fault. I must have not been clear but I removed z address  and rpc user name and password before posting online. 

here is the new set of errors,
> z-nomp@0.0.9 start /home/miningcore/Downloads/z-nomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

undefined:1
{"logLevel":"debug","logColors":true,"cliPort":17117,"clustering":{"enabled":true,"forks":"auto"},"defaultPoolConfigs":{"blockRefreshInterval":500,"jobRebroadcastTimeout":55,"connectionTimeout":600,"emitInvalidBlockHashes":false,"validateWorkerUsername":true,"tcpProxyProtocol":false,"banning":{"enabled":true,"time":600,"invalidPercent":50,"checkThreshold":500,"purgeInterval":300},"redis":{"host":"127.0.0.1","port":6379,}},"website":{"enabled":true,"host":"secedgardirect.com","port":8080,"stratumHost":"0.0.0.0","stats":{"updateInterval":30,"historicalRetention":14400,"hashrateWindow":300},"adminCenter":{"enabled":false,"password":"password"},"tlsOptions":{"enabled":false,"cert":"","key":""}},"redis":{"host":"127.0.0.1","port":6379},"switching":{"switch1":{"enabled":false,"algorithm":"sha256","ports":{"3333":{"diff":10,"varDiff":{"minDiff":16,"maxDiff":512,"targetTime":15,"retargetTime":90,"variancePercent":30}}}},"switch2":{"enabled":false,"algorithm":"scrypt","ports":{"4444":{"diff":10,"varDiff"

SyntaxError: Unexpected token } in JSON at position 423
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/miningcore/Downloads/z-nomp/init.js:27:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! z-nomp@0.0.9 start: `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the z-nomp@0.0.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/miningcore/.npm/_logs/2018-08-07T04_45_25_200Z-debug.log

**Comment by egyptianbman** [comment]
Please read the eror messages and google them when possible before posting issues here. This is also not an issue with z-nomp:

```
SyntaxError: Unexpected token } in JSON at position 423
```

Your configuration's JSON doesn't seem to be valid.

**Comment by osheen2241** [comment]
Thanks anyway, I'm back to  the original error that I posted. I'll figure it out. 

/home/miningcore/Downloads/z-nomp/node_modules/bs58check/base.js:41
    if (!payload) throw new Error('Invalid checksum')

**Comment by egyptianbman** [comment]
If you follow the stack trace and search for:
- z-nomp - https://github.com/z-nomp/z-nomp
- stratum-pool - https://github.com/z-nomp/node-stratum-pool
- equihashverify - https://github.com/z-nomp/equihashverify
- bitcoinjs-lib - https://github.com/z-nomp/bitcoinjs-lib

You can then look at that line of code and see what it's trying to do. This will usually reveal what the problem is.

In your case, it's trying to generate a checksum of a value that's coming from the config file that's empty. Look for empty strings `""`

**Comment by osheen2241** [comment]
I left reward recipient blank. I was under the assumption it was optional. Good stuff!

**Comment by egyptianbman** [comment]
I know you have to put an address if there's an entry there. You might be able to make it an empty object.

**Comment by osheen2241** [comment]
thanks @egyptianbman , the only issue I have now is this using daemon version 1.1.0 

2018-08-07 05:33:55 ERROR: ContextualCheckTransaction: overwinter is active
2018-08-07 05:33:55 ERROR: ProcessNewBlock: AcceptBlock FAILED
2018-08-07 05:33:55 ERROR: ReadBlockFromDisk: OpenBlockFile failed for CBlockDiskPos(nFile=-1, nPos=0)

I cant seem to get any z-nomp version to verifiebly mine an overwinter block. How can we fix this issue? 

2018-08-06 22:37:33 [Pool]	[zcash_testnet] (Thread 2) We thought a block was found but it was rejected by the daemon, share data: {"job":"ccd3","ip":"::ffff:192.168.1.157","port":3032,"worker":"tmDRtohUPp9QGrCW9NSzq9RcFBJW1sGybgu.noname","height":275050,"difficulty":10.49698698,"shareDiff":"11.66588048","blockDiff":7.435865434,"blockDiffActual":7.435865434,"blockHash":"0000af8dfffceb81d3ba8172fce0e72aaa59cfb0060b7b8940fce3da8f54fbfb","error":{"unknown":"check coin daemon logs"}}

Thanks

**Comment by osheen2241** [comment]
just added this to transaction.js and its mining overwinter blocks. I think?

function Transaction () {
  this.version = 1
  this.locktime = 0
  this.ins = []
  this.outs = []
  this.joinsplits = []
  this.zcash = true;
  this.version = Math.max((this.version||3), 3);
  this.versionGroupId=0x03c48270;
  this.expiry=0;
}


\\

2018-08-06 23:54:47 [Pool]	[zcash_testnet] (Thread 1) Block found: 00007b9fb82b6ea945dc0c996c88c1025e3ec8ba40b1fdc35bcf1501484c401d by tmDRtohUPp9QGrCW9NSzq9RcFBJW1sGybgu.noname


\\


2018-08-07 06:59:31 proof-of-work found  
  hash: 0000140259315588c58d3a17a6c5d673489d925cea06ecbaf74f34df9d405dfb  
target: 000158a300000000000000000000000000000000000000000000000000000000
2018-08-07 06:59:31 CBlock(hash=0000140259315588c58d3a17a6c5d673489d925cea06ecbaf74f34df9d405dfb, ver=4, hashPrevBlock=000024090134cd1278cc5003553d8bf7bad08602951def7e772302a606b987f5, hashMerkleRoot=fd3573d5f67817ec17aad4e1a8ccd2a392f73f4dad90991f15e06c323d240c09, hashReserved=0000000000000000000000000000000000000000000000000000000000000000, nTime=1533625170, nBits=1f0158a3, nNonce=0000f7801ab15ed71ee0348753110510cb16780923c6ea0ac70e051aa03d001a, vtx=1)
  CTransaction(hash=fd3573d5f6, ver=3, fOverwintered=1, nVersionGroupId=03c48270, vin.size=1, vout.size=2, nLockTime=0, nExpiryHeight=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 038132040101)
    CTxOut(nValue=10.00000000, scriptPubKey=OP_DUP OP_HASH160 505fdbabc881)
    CTxOut(nValue=2.50000000, scriptPubKey=OP_HASH160 2a71f51b268f74eb3ee)

  vMerkleTree:  fd3573d5f67817ec17aad4e1a8ccd2a392f73f4dad90991f15e06c323d240c09

testnet wallet does not update though, is that correct?

**Comment by osheen2241** [comment]
fixed the overwinter issue!

Cheers

**Comment by egyptianbman** [comment]
Do you have `"overwinter": true` in your coin config?

**Comment by osheen2241** [comment]
Actually it works perfectly, 

https://explorer.testnet.z.cash/address/tmDRtohUPp9QGrCW9NSzq9RcFBJW1sGybgu

actually in the testnet config there was no line for overwinter true. Yet it worked, should I remove that line from the mainnet config?

{
    "name": "zcash_testnet",
    "symbol": "taz",
    "algorithm": "equihash",
    "requireShielding": true,
    "payFoundersReward": true,
    "percentFoundersReward": 20,
    "maxFoundersRewardBlockHeight": 849999,
    "foundersRewardAddressChangeInterval": 17709.3125,
    "vFoundersRewardAddress": [

Nevermind, I see what i did with the code.

**Comment by Gumbees** [comment]
@osheen2241 Remember ZEC testnet is not functional because of sapling being active. We do not support that yet.
