### ISSUE TITLE
who's Bill Kendrick 

### ISSUE THREAD

**Issue by osheen2241** [s-nomp/s-nomp#36]
this message popped up on screen while mining. Any ideas?

2018-08-07 21:36:10 [Pool]	[zcash] (Thread 2) No new blocks for 55 seconds - updating transactions & rebroadcasting work
Bill Kendrick2018-08-07 21:36:38 [Payments]	[zcash] Finished interval - time spent: 2ms total, 1ms redis, 2ms daemon RPC
2018-08-07 21:37:06 [Pool]	[zcash] (Thread 4) No new blocks for 55 seconds - updating transactions & rebroadcasting work

**Comment by egyptianbman** [comment]
I'm not sure what screen this popped up on. Can you elaborate on that?

**Comment by 0x6b656e** [comment]
@osheen2241 That string is no where in the code, so its obviously Isolated to something on your server.

**Comment by egyptianbman** [comment]
This sort of thing happens to me all the time. If you type text into a terminal, it will appear on the screen. I would bet this is the case here. You had the screen up and typed out that name, then more output was generated.
