### ISSUE TITLE
Add pool fee to /api/stats

### ISSUE THREAD

**Issue by egyptianbman** [s-nomp/s-nomp#37]
Various sites query our pools for information. It would be useful for them to be able to get the fees for every coin.

One problem with fetching this automatically from the pool configs is some pool operators donate to the coin community so summing up all the reward recipients wouldn't be an accurate fee.

Maybe we should add another item below it named `poolFee` with a comment that this is only used for the stats api.

**Comment by zzzpotato** [comment]
Even if a % is donated to the community, isn't it still "technically" a fee charged to the miners though? The only problem I see with `poolFee` for the API is it remaining incorrect when pool ops modify their actual fee's. This could lead to inaccurate/misleading API results which I think is the issue you're trying to correct now.

**Comment by egyptianbman** [comment]
This is why I suggested putting the config option in the pool config and not the coin config. If it was in the coin config, out of sight, out of mind. With it being in the pool config right below the reward recipients, the pool operator would have to intentionally ignore it.

**Comment by zzzpotato** [comment]
True and ultimately anything could be modified to show whatever they want so my concern is more of a non issue.

**Comment by zzzpotato** [comment]
I've tested this addition in #39
