### ISSUE TITLE
Pool Name in config.json

### ISSUE THREAD

**Issue by Gumbees** [s-nomp/s-nomp#4]
Looking to make this easier is to add the pool name as a configurable option. Will need to be converted to hex by znomp. This is so the explorers can show the mined by "" for every pool. Default name should be z-nomp.

**Comment by Gumbees** [comment]
@egyptianbman assigned to you since you took over the hex in node-stratum-pool :).

**Comment by egyptianbman** [comment]
Ah, this is complete. I chose to store the hex in the configs, not string so that we don't waste compute power generating a hex constantly.
