### ISSUE TITLE
All new blocks get rejected

### ISSUE THREAD

**Issue by williamsmithza** [s-nomp/s-nomp#48]
I am running snowgem on my pool and new blocks get rejected. Not only one but all of them. Please help here is the log from the daemon. Please help or advise urgently.

2018-08-14 07:57:56 ERROR: ContextualCheckBlock: founders reward missing
2018-08-14 07:57:56 ERROR: ProcessNewBlock: AcceptBlock FAILED
2018-08-14 07:57:56 ERROR: ReadBlockFromDisk: OpenBlockFile failed for CBlockDiskPos(nFile=-1, nPos=0)

And here is the pool error

2018-08-14 09:57:56 [Pool]      [snowgem] (Thread 7) We thought a block was found but it was rejected by the daemon, share data: {"job":"d20f","ip":"::ffff:197.184.41.156","port":1234,"worker":"s1aKn13it5hsXHdUhFUXmp8f2Wj2tqo1CAi.ATR1080Rig","height":333304,"difficulty":0.65186611,"shareDiff":"1072.29723719","blockDiff":404.449343535,"blockDiffActual":404.449343535,"blockHash":"000001e8f0660a8a2a21879143f3775006233fba2b682afcf2525b3bb2dab566","error":{"unknown":"check coin daemon logs"}}

**Comment by Punkoivan** [comment]
hello @williamsmithza ,
did you set up dev rewards for snowgem?

**Comment by williamsmithza** [comment]
Ok now that you mention it, I did change or remove some of the addresses in founders rewards. Did restore now to origional addresses. So my thinking is you can add more addresses for lets say pool owner etc but you cannot remove origional dev addresses.  Am I correct ? So it is actually best not to alter any dev addresses but rather to add reward recepients in pool config.

**Comment by Punkoivan** [comment]
Sure, for pool owner please edit file in pool_configs directory, section is (started at line 20):
```
    "rewardRecipients": {
```

And these addresses you must have in coins directory:
```
    "vFoundersRewardAddress": [
                "s3d27MhkBRt3ha2UuxhjXaYF4DCnttTMnL1",
                "s3Wws6Mx3GHJkAe8QkNr4jhW28WU21Fp9gL",
                "s3QD18CKEA9Cw4kgnssnmk4rbf9Y3rU1uWG",
                "s3esoTmHdcXdDwCkoGSxC4YkfzBo1ySuher",
                "s3Q8NwoBv4aq9RRvqjT3LqN9TQnZrS2RdcV",
                "s3ix12RLstrzFEJKVsbLxCsPuUSjAqs3Bqp",
                "s3bCvm5zDv9KYFwHxaZjz2eKecEnbdFz98f",
                "s3UfvUuHahzTmYViL3KrGZeUPug69denBm3",
                "s3gmzNUmttwDJbUcpmW4gxVqHf3J58fDKpp",
                "s3YuWMW4Kpij7gW91WHLhjfi5Dwc7dKyPNn",
                "s3k2MaTdZyFBqyndrHdCDFnET5atCdC4iod",
                "s3YFHxL9euG89LMgPT5wGka4Ek8XVyw4FWG",
                "s3TKKkNnvBXphdv4ce84UKePdssWLHGBe1A",
                "s3PLrY7e7jzzAxnMY7A6GkjhkGc1CVkuEoi",
                "s3Ug8VAGcUijwD6QMhyFcCYXQEFABaA9VFy",
                "s3b4DAbbrTb4FPz3mHeyE89fUq6Liqg5vxX",
                "s3cM379BTJyCe5yJC4jkPn6qJwpZaHK2kXb",
                "s3TKWLar6bZEHppF4ZR1MbPuBfe33a1bHX9",
                "s3UpY6Q3T3v3F7MEpNDnV3rTucLEJkkHR4q",
                "s3eWx3DcwLiusTBfhWu6z7zM4TffaV1Ng9r"
    ],
```

I believe that should be a solution.

Ivan/Nibirupool

**Comment by williamsmithza** [comment]
Will follow your advise. Thanx buddy. You are a star.  Was giving me a lot of headaches because of my stupidity.

**Comment by Punkoivan** [comment]
You are welcome.
Please let us know if this solve your issue.

**Comment by williamsmithza** [comment]
I gonna try now.

**Comment by williamsmithza** [comment]
Can you however edit the 5% dev reward to 1% ?

**Comment by Punkoivan** [comment]
Nope, it's hardcoded in daemon and when it doesn't meet requirements, network simply reject your blocks.

**Comment by williamsmithza** [comment]
Thanx, busy mining now to try and find blocks.

**Comment by williamsmithza** [comment]
Thanx you are a hero. Pool works and block submitted succesfully.

**Comment by Punkoivan** [comment]
No problem, glad to help ;)

Ivan

**Comment by Jerry170617** [comment]
@williamsmithza  Hey brother, what version are you using, a master network or a test network? I have the same problem.
