### ISSUE TITLE
Variable shielding amount set in coins/coin.json

### ISSUE THREAD

**Issue by Gumbees** [s-nomp/s-nomp#5]
Some coins reward 50 and some like 20000. The global 100 is not the best one for all coins and this causes payments to hang. This should be a configurable option.

**Comment by Gumbees** [comment]
Shielding amount has been completely removed. We'll be rewriting the code base to use z_shieldcoinbase instead of sendmany for coins that support it.

**Comment by egyptianbman** [comment]
It doesn't look like this was removed -- am I just confused?

https://github.com/s-nomp/s-nomp/blob/b2c5e8945d7b2cec4821f6d02a443f76e645dc16/libs/paymentProcessor.js#L298-L299
