### ISSUE TITLE
Please Help Snowgem rejects blocks

### ISSUE THREAD

**Issue by williamsmithza** [s-nomp/s-nomp#52]
We thought a block was found but it was rejected by the daemon, share data: {"job":"ccef","ip":"::ffff:169.239.45.72","port":1234,"worker":"s1aKn13it5hsXHdUhFUXmp8f2Wj2tqo1CAi.1060X4","height":339100,"difficulty":0.50459162,"shareDiff":"564.48000227","blockDiff":448.408819992,"blockDiffActual":448.408819992,"blockHash":"000003a0cc55ab2cb6e58a8b14d1943e0bd3211fddae5302b9acc2a7dcc135a3","error":{"confirmations":-1}}

Everything runs smooth for a while and then all of a sudden starts rejecting blocks - any idea why

**Comment by egyptianbman** [comment]
1. Can you provide your coin configuration?
2. This doesn't happen all the time, but just sometimes? Can you estimate how frequently?
3. Are you sure these aren't orphaned blocks?
4. Is your node fully up to date? Also, can you provide the log output from the node when this happens?

**Comment by williamsmithza** [comment]
Coin configuration

{
    "name": "snowgem",
    "symbol": "xsg",
    "algorithm": "equihash",
    "parameters": {
        "N": 144,
        "K": 5,
        "personalization": "sngemPoW"
    },
    "requireShielding": true,
    "payFoundersReward": true,
    "percentFoundersReward": 5,
    "maxFoundersRewardBlockHeight": 2106399,
    "foundersRewardAddressChangeInterval": 105320,
    "vFoundersRewardAddress": [
        "s3d27MhkBRt3ha2UuxhjXaYF4DCnttTMnL1",
	"s3Wws6Mx3GHJkAe8QkNr4jhW28WU21Fp9gL",
	"s3QD18CKEA9Cw4kgnssnmk4rbf9Y3rU1uWG",
	"s3esoTmHdcXdDwCkoGSxC4YkfzBo1ySuher",
	"s3Q8NwoBv4aq9RRvqjT3LqN9TQnZrS2RdcV",
	"s3ix12RLstrzFEJKVsbLxCsPuUSjAqs3Bqp",
	"s3bCvm5zDv9KYFwHxaZjz2eKecEnbdFz98f",
	"s3UfvUuHahzTmYViL3KrGZeUPug69denBm3",
	"s3gmzNUmttwDJbUcpmW4gxVqHf3J58fDKpp",
	"s3YuWMW4Kpij7gW91WHLhjfi5Dwc7dKyPNn",
	"s3k2MaTdZyFBqyndrHdCDFnET5atCdC4iod",
	"s3YFHxL9euG89LMgPT5wGka4Ek8XVyw4FWG",
	"s3TKKkNnvBXphdv4ce84UKePdssWLHGBe1A",
	"s3PLrY7e7jzzAxnMY7A6GkjhkGc1CVkuEoi",
	"s3Ug8VAGcUijwD6QMhyFcCYXQEFABaA9VFy",
	"s3b4DAbbrTb4FPz3mHeyE89fUq6Liqg5vxX",
	"s3cM379BTJyCe5yJC4jkPn6qJwpZaHK2kXb",
	"s3TKWLar6bZEHppF4ZR1MbPuBfe33a1bHX9",
	"s3UpY6Q3T3v3F7MEpNDnV3rTucLEJkkHR4q",
	"s3eWx3DcwLiusTBfhWu6z7zM4TffaV1Ng9r"
    ],
    "peerMagic": "24c82764",

    "explorer": {
        "txURL": "https://insight.snowgem.org/tx/",
        "blockURL": "https://insight.snowgem.org/block/",
        "_comment_explorer": "This is the coin's explorer full base url for transaction and blocks i.e. (https://explorer.coin.com/tx/). The pool will automatically add the transaction id or block id at the end."
    }
}

**Comment by williamsmithza** [comment]
Well it happens quite frequently. Some blocks get accepted but most get rejected. Lets say it works fine for about an hour and then for about 6 hours rejects new blocks

**Comment by williamsmithza** [comment]
where do i get the logs of the node

**Comment by egyptianbman** [comment]
Check the `debug.log` file in your coin's data directory.

**Comment by williamsmithza** [comment]
Am trying to check trough the logs quickly but i think i cleared the logs and restarted the daemon

**Comment by williamsmithza** [comment]
Nope i think i deleted

**Comment by williamsmithza** [comment]
rpcuser=password
rpcpassword=password
rpcallowip=127.0.0.1
server=1
daemon=1
listen=1
txindex=1
rpcport=16112
port=16113
rpcbind=0.0.0.0
rpcworkqueue=64
addnode=127.0.0.1:16112
addnode=45.76.137.106
addnode=45.32.79.163
addnode=45.77.70.230
addnode=45.77.160.169
addnode=207.148.68.108
addnode=104.24.117.245
addnode=142.44.214.53
addnode=158.69.253.17
addnode=104.24.123.22
addnode=104.25.244.104
addnode=24.129.114.44
addnode=108.249.146.109
addnode=46.254.16.114

blocknotify= /home/user/s-nomp/scripts/blocknotify 127.0.0.1:17117 xsg %s

**Comment by williamsmithza** [comment]
I will see how it goes as I also changed the block notify from 

blocknotify=node /home/user/s-nomp/scripts/cli.js blocknotify xsg %s

to 

blocknotify= /home/user/s-nomp/scripts/blocknotify 127.0.0.1:17117 xsg %s

**Comment by williamsmithza** [comment]
Can you possibly tell me how to let the pool show on the explorer mined by pool name and url

**Comment by egyptianbman** [comment]
@williamsmithza sorry about the delay, be sure to check your configuration:

https://github.com/s-nomp/s-nomp/blob/b2c5e8945d7b2cec4821f6d02a443f76e645dc16/config_example.json#L32-L33
