### ISSUE TITLE
Which version of zcash wallet should be used at present?

### ISSUE THREAD

**Issue by Jerry170617** [s-nomp/s-nomp#61]
Which version of zcash wallet should be used at present?

**Comment by Gumbees** [comment]
@zheng9980419 you can use the latest version. TESTNET is not functional in s-nomps current state due to sapling being active. We hope to have that patched this month for sapling support.

**Comment by zheng9980419** [comment]
Is it normal to use 2.0 version of the main network?

**Comment by Jerry170617** [comment]
Zcash 2.0 s-nomp can normally block out?

**Comment by Jerry170617** [comment]
@nettts

**Comment by Gumbees** [comment]
@zheng9980419 zcash 2.0 will work fine with s-nomp. Just not for the use of testnet.

**Comment by Jerry170617** [comment]
@nettts thank you

**Comment by bcmonster** [comment]
What about Zen TestNet?
