### ISSUE TITLE
Failed at the equihashverify@0.0.10 install script

### ISSUE THREAD

**Issue by hysystem** [s-nomp/s-nomp#64]
../crypto/common.h:11:20: fatal error: sodium.h: No such file or directory
 #include "sodium.h"
                    ^
compilation terminated.
make: *** [Release/obj.target/equihashverify/arith_uint256.o] Error 1
make: Leaving directory `/data/s-nomp/node_modules/equihashverify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v10.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Linux 3.10.0-693.2.2.el7.x86_64
gyp ERR! command "/root/.nvm/v10.8.0/bin/node" "/root/.nvm/v10.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/s-nomp/node_modules/equihashverify
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! equihashverify@0.0.10 install: `env V=1 node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the equihashverify@0.0.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-10T11_34_31_142Z-debug.log

**Comment by Gumbees** [comment]
If you downloaded this to your $home directory please don't run this as root. Run s-nomp as a normal user. It doesn't need elevated.

**Comment by egyptianbman** [comment]
Please do a Google search for the error before creating an issue:

https://www.google.com/search?q=fatal+error%3A+sodium.h%3A+No+such+file+or+directory&oq=fatal+error%3A+sodium.h%3A+No+such+file+or+directory&aqs=chrome..69i57.239j0j7&{google:bookmarkBarPinned}sourceid=chrome&{google:instantExtendedEnabledParameter}{google:omniboxStartMarginParameter}ie=UTF-8

The second result leads to this: https://github.com/aionnetwork/aion_miner/issues/6#issuecomment-365069725

**Comment by hysystem** [comment]
thanks!!
