### ISSUE TITLE
Invalid solution: invalid collision length between StepRows 

### ISSUE THREAD

**Issue by Jerry170617** [s-nomp/s-nomp#66]
Invalid solution: invalid collision length between StepRows 
X[i]   = 08e47103f97503fd2e0d589b0c114008de6e0eb22f0e7ded024c30033c94
 X[i+1] = 0bddec0637c103a39602dd850a431508589802cb900765e1059ef4072289

**Comment by Jerry170617** [comment]
A9 ASIC

**Comment by Gumbees** [comment]
@zheng9980419 

Please provide what coin and your coin config, and ASIC script. You may also join our discord to get help faster. https://discord.gg/ctR5np

**Comment by Jerry170617** [comment]
{
    "enabled": true,
    "coin": "zec.json",

    "address": "t1HzDdkMxkz********GhuSbS4H",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "zcZtFSNW5VorQZW2gaCSv********************************jyZWWbSZnvtQmJdn3engGdpXco",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "t1HzDdkMxkz********GhuSbS4H",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

    "invalidAddress":"t1HzDdkMxkz********GhuSbS4H",
    "_comment_invalidAddress": "Invalid addresses will be converted to the above",

    "walletInterval": 2.5,
    "_comment_walletInterval": "Used to cache coin stats",

    "rewardRecipients": {
        "t1HzDdkMxkz********GhuSbS4H": 0.1
    },

    "tlsOptions": {
        "enabled": false,
        "serverKey": "",
        "serverCert": "",
        "ca": ""
    },

    "paymentProcessing": {
        "enabled": true,
        "minConf": 10,
        "paymentMode": "pplnt",
        "_comment_paymentMode": "prop, pplnt",
        "paymentInterval": 120,
        "minimumPayment": 10,
        "maxBlocksPerPayment": 3,
        "daemon": {
            "host": "127.0.0.1",
            "port": 8930,
            "user": "*****",
            "password": "******"
        }
    },

    "ports": {
        "3036": {
            "diff": 0.5,
            "tls": false,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 36,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "poolId": "main",
    "_comment_poolId": "use it for region identification: eu, us, asia or keep default if you have one stratum instance for one coin",

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 8930,
            "user": "*******",
            "password": "*******"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "zec",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}

**Comment by Jerry170617** [comment]
coin：zcash

**Comment by Jerry170617** [comment]
Innosilicon A9 ：
Algorithm: Equhash
Calculations: 50Ksol / S(+-8 %)
Power consumption: 620W + / -8 %
Size:(L) 360mm *(W) 125mm *(H) 155mm
Weight: 5.13 KG(excluding power supply)
PSU: Output power greater than 1000W, 7 * PCI-E6Pin
Operating temperature: 0-85 °C
Network Type: Ethernet

**Comment by Jerry170617** [comment]
I run s-nomp Branch: feat / zero-founders-reward.
The above problems have arisen.
The following problems were encountered
Invalid solution: invalid collision length between StepRows
X[i] = 08e47103f97503fd2e0d589b0c114008de6e0eb22f0e7ded024c30033c94
X[i+1] = 0bddec0637c103a39602dd850a431508589802cb900765e1059ef4072289

**Comment by Gumbees** [comment]
@zheng9980419 The ASIC you have does not support ZERO currency. Also, you should not use the ZERO config files actively yet. The fork isn't until mid September. 

That branch isn't in master yet because it hasn't been tested. Nothing was changed with ZEC in that update though. 

If you're mining on testnet, testnet isn't supported. Invalid collisions can also mean the difficulty is too low. Use this difficulty setting and report back the results.

```
    "3036": {
        "diff": 36,
        "tls": false,
        "varDiff": {
            "minDiff": 32,
            "maxDiff": 128,
            "targetTime": 15,
            "retargetTime": 60,
            "variancePercent": 30
        }
```

**Comment by Jerry170617** [comment]
Testing in progress.
According to the information I have so far, I wonder if it is possible to make a normal block?

**Comment by Jerry170617** [comment]
The problem has not been solved, but the frequency of occurrence seems to be much less.

**Comment by zheng9980419** [comment]
Invalid solution: invalid collision length between StepRows
X[i]   = 00cb6d03382f0d2b41051779035be606ed8b0e0d030d268d0b0e150a077f
X[i+1] = 05b8110d50a806f2950b0a3009068c06d41a0285880b8555022fa6098a75
2018-09-12 02:53:53 [Pool]      [zcash] (Thread 2) Share rejected: {"job":"cce2","ip":"::ffff:112.113.93.19","worker":"t1XVDTvT7w9NiaounWMT4jfT79we6wQJGKz.A9TAH100x107","difficulty":98.04882267,"error":"invalid solution"}

**Comment by Gumbees** [comment]
@zheng9980419 it is. It'll take you forever by yourself with ZEC and 1 A9. If you have multiple A9's using the same worker you'll have to up the difficulty more.

Four difficulties to account for when running a pool. You can account for multiple ones in variance difficulty to use less ports.

1. GPU Worker
2. ASIC Worker
3. GPU Farm
4. ASIC Farm / Nicehash.

You could accomplish this with two ports.

````
  "3036": {
        "diff": 0.5,
        "tls": false,
        "varDiff": {
            "minDiff": 0.05
            "maxDiff": 128,
            "targetTime": 5,
            "retargetTime": 30,
            "variancePercent": 15
         }
     }, // GPU RIGS or ASICS (individual workers)
    
    "3037": {
         "diff": 128,
         "tls": false,
         "varDiff": {
             "minDiff": 128,
             "maxDiff": 512,
             "targetTime": 5,
             "retargetTime": 30,
             "variancePercent": 15
          }
      }, // GPU-ASIC FARMS / NICEHASH (pooled as 1 worker)
        
```

**Comment by Jerry170617** [comment]
Invalid solution: invalid collision length between StepRows
X[i]   = 00cb6d03382f0d2b41051779035be606ed8b0e0d030d268d0b0e150a077f
X[i+1] = 05b8110d50a806f2950b0a3009068c06d41a0285880b8555022fa6098a75
2018-09-12 02:53:53 [Pool]      [zcash] (Thread 2) Share rejected: {"job":"cce2","ip":"::ffff:112.113.93.19","worker":"t1XVDTvT7wxxxxxxxxxxxQJGKz.A9TAH100x107","difficulty":98.04882267,"error":"invalid solution"}

**Comment by Gumbees** [comment]
@zheng9980419 are they constant or are you getting them only once every few shares?

**Comment by Jerry170617** [comment]
getting them only once every few shares.

**Comment by Gumbees** [comment]
@zheng9980419 Okay. Did you try with a GPU to test with against your asic? Just to make sure the ASIC is okay?

**Comment by Jerry170617** [comment]
GPU   or   ASIC . It's all wrong.
Branch: feat / zero-founders-reward and Branch:master  What's the difference?

**Comment by Gumbees** [comment]
@zheng9980419

It is normal to get these every few shares. Especially with ASICs.

The only difference is a coin config file which you aren't using. 

If there was a core issue outside the config every solution would be invalid. 

Try your ASIC on ZEN testnet and you can ensure it's good to go. Or try mining votecoins which is a ZEC replica. If you find a votecoin block you're good in ZEC.

ZEC testnet will not function currently due to sapling.

**Comment by Jerry170617** [comment]
How do I solve this problem?

**Comment by Gumbees** [comment]
@zheng9980419 are you still having this issue with your ASICS?

**Comment by AlexSpain** [comment]
We have same at Horizen coin with s-nomp
2018-10-22 20:53:15 [Pool]      [horizen] (Thread 5) Block notification via RPC polling
Invalid solution: invalid collision length between StepRows
X[i]   = 068f1b08fa2404c40706ca100ef58106498e0d83c104ce5a07f4d1048b3c
X[i+1] = 08744a044be20a84440c1f620b26af0b18a500ec530f11c90ac40708e493

**Comment by Gumbees** [comment]
@alexspain it is normal to get these sometimes. It's when it's a constant spam when it is an issue. Happens more with ASICs and is usually solved by highering the difficulty when it happens more often or not.

I am closing this.
