### ISSUE TITLE
A9 asic submits lots of "duplicate shares"

### ISSUE THREAD

**Issue by zzgang** [s-nomp/s-nomp#76]
A9 asic for mining ZEC submits lots of "duplicate shares", Should i change something?

Or A9's fault?

**Comment by dacelee** [comment]
Please check your configuration.

I didn't use any problems.

**Comment by Gumbees** [comment]
@zzgang do you save logs of your A9 miner and the log of s-nomp?

**Comment by zzzpotato** [comment]
Closing until more info can be provided
