### ISSUE TITLE
Insufficient funds (12.46885) to process payments (12.469049); possibly waiting for txs.

### ISSUE THREAD

**Issue by zlatinov** [s-nomp/s-nomp#77]
* Pool config

<details>

```
{
    "enabled": true,
    "coin": "zcl.json",

    "address": "t1...Qe",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "zc...3f",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "t1...5C",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

    "invalidAddress":"t1...5C",
    "_comment_invalidAddress": "Invalid addresses will be converted to the above",

    "walletInterval": 10,
    "_comment_walletInterval": "Used to cache coin stats",

    "rewardRecipients": {
        "t1..Ux": 0.25
    },

    "tlsOptions": {
        "enabled": false,
        "serverKey": "",
        "serverCert": "",
        "ca": ""
    },

    "paymentProcessing": {
        "enabled": true,
        "minConf": 10,
        "paymentMode": "pplnt",
        "_comment_paymentMode": "prop, pplnt",
        "paymentInterval": 600,
        "minimumPayment": 0.1,
        "maxBlocksPerPayment": 1,
        "daemon": {
            "host": "...",
            "port": ...,
            "user": "...",
            "password": "..."
        }
    },

    "ports": {
        "5032": {
            "tls": false,
            "diff": 2,
            "varDiff": {
                "minDiff": 2,
                "maxDiff": 2,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "poolId": "main",
    "_comment_poolId": "use it for region identification: eu, us, asia or keep default if you have one stratum instance for one coin",

    "daemons": [
        {
            "host": "...",
            "port": ...,
            "user": "...",
            "password": "..."
        }
        ],
    "p2p": {
        "enabled": true,
        "host": "...",
        "port": ...,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "zcl",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}
```

</details>

* Coin config

<details>

```
{
    "name": "zclassic",
    "symbol": "zcl",
    "algorithm": "equihash",
    "requireShielding": true,
    "peerMagic": "24e92764",
    "txfee": 0.000001,
    "explorer": {
        "txURL": "http://explorer.zclmine.pro/tx/",
        "blockURL": "http://explorer.zclmine.pro/block/",
        "_comment_explorer": "This is the coin's explorer full base url for transaction and blocks i.e. (https://explorer.coin.com/tx/). The pool will automatically add the transaction id or block id at the end."
    }
}
```

</details>

```
$ zcash-cli listunspent
[
  {
    "txid": "db...84",
    "vout": 0,
    "generated": false,
    "address": "t1...5C",
    "account": "",
    "scriptPubKey": "76...ac",
    "amount": 12.46885000,
    "confirmations": 485,
    "spendable": true
  }
]
```

The error is on the first block. Had the same problem, while mining Hush and BTCPrivate, with the first block. The difference this time is that the pool reward address is in an exchange. Is this a bad idea, since it's amount is not shielded? The amount in the error (`12.469049`) is with the reward subtracted, so it shouldn't be an issue?

I've read the code and am wondering - [shouldn't the trx fee be subtracted here too](https://github.com/s-nomp/s-nomp/blob/c78a92caeacf8d2dc7bb834fcc4ee8e9138f4dae/libs/paymentProcessor.js#L868)?

On a side note - why are the shielding transactions not using the fee, which is setup in the coin config?

Thank you in advance.

**Comment by zlatinov** [comment]
Are the taxes for shielding trxs taking into consideration for this?

After getting a second block, the first one is paid, but the second one is stuck the same way. I guess the wallet needs enough satoshis, outside of rewards, to cover the taxes.

Is this the expected behavior? Maybe it would be better to have this as an option in the configs - if the taxes should be covered manually by the pool, outside of the rewards, or from the rewards.

**Comment by bcmonster** [comment]
Its takes a 100 to confirm it.  After that shielding.  It should pay out by about 140 confirmations.  Normal for shielded coins.

**Comment by zlatinov** [comment]
It was at around 900 confirmations. Output of `zcash-cli listunspent` is in my original post, the amount was shielded and available in the `tAddress`.

**Comment by dacelee** [comment]
rpcworkqueue=512
"paymentInterval": 480

**Comment by dacelee** [comment]
I set it up to solve the problem.

**Comment by Gumbees** [comment]
@zlatinov you should put a small percentage of the rewards to you Block Founders Reward address. These will then get shielded/unshielded to your taddress for sending then. It's a process I follow myself. Be sure the percentage is enough to cover all taxes. 

you should run a z_shieldcoinbase on both t addresses to be sure all funds have been shielded.. if there are any left over send them to your payout address when done.

**Comment by zlatinov** [comment]
@nettts, thank you.

This sounds like a rather hackish solution though. Can there be an option in the pool to take the taxes out of the block reward automatically? This way the pool won't need any outside funds to operate.

**Comment by Gumbees** [comment]
@zlatinov Post an issue requesting this feature. We'll prioritize based on the demand :).

**Comment by egyptianbman** [comment]
Pull requests are also appreciated if you find the time to fix this issue yourself; thanks!
