### ISSUE TITLE
Does BitcoinZ is still supported?

### ISSUE THREAD

**Issue by pavlovdog** [s-nomp/s-nomp#89]
As I have heard, Bitcoinz has moved to the Zhash algorithm, instead of Equihash. Does it mean that the s-nomp pool can't be used with Bitcoinz?

**Comment by egyptianbman** [comment]
Zhash **is** Equihash but instead of being Equihash 200,9, it's Equihash 144,5. Several coins in addition to BitcoinZ have migrated away from 200,9 and yes, this pool supports them.
