### ISSUE TITLE
Share Rejected

### ISSUE THREAD

**Issue by BaikalMine** [s-nomp/s-nomp#90]
How to solve this problem? How to solve this problem? ZeroClassic Coin

Share rejected: {"job":"ccce","ip":"::ffff:90.188.239.249","worker":"t1Nwh2urX25fWNujs6zuwsqYe9PcqBTrJHp.1","difficulty":0.05,"error":"Error: Incorrect size of solution (806), expected 2694"}

**Comment by zzzpotato** [comment]
I believe this is due to an incorrect coins json. See #91 and try the changes

**Comment by zzzpotato** [comment]
I'm going to close this issue now that the PR has been merged. Reopen it or join discord if you continue to have issues.
