### ISSUE TITLE
No pool payouts! Insufficient funds (15.38) to process payments (32.4497); possibly waiting for txs.

### ISSUE THREAD

**Issue by TheBudda** [s-nomp/s-nomp#93]
2018-11-09 21:16:43 [Payments]  [anon] sendZToT is waiting, too many z_sendmany operations already in progress.
2018-11-09 21:16:43 [Payments]  [anon] Insufficient funds (15.38) to process payments (32.4497); possibly waiting for txs.
2018-11-09 21:16:43 [Payments]  [anon] Finished interval - time spent: 4ms total, 1ms redis, 3ms daemon RPC

**Comment by TheBudda** [comment]
Here is the debug.log. Can you please tell me what other logs you need and where I can find them?

[debug.log](https://github.com/s-nomp/s-nomp/files/2567535/debug.log)

**Comment by TheBudda** [comment]
Here is my pool_config file

{
    "enabled": true,
    "coin": "anon.json",

    "address": "********************xnp9",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "*********************************8Mw",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "******************rvRx",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

    "invalidAddress":"**********************EmKT",
    "_comment_invalidAddress": "Invalid addresses will be converted to the above",

    "walletInterval": 2.5,
    "_comment_walletInterval": "Used to cache coin stats",

    "rewardRecipients": {
        "*****************dUt": 0.1
    },

    "tlsOptions": {
        "enabled": true,
        "serverKey": "/etc/letsencrypt/live/anon.cryptoblock.uk/privkey.pem",
        "serverCert": "/etc/letsencrypt/live/anon.cryptoblock.uk/cert.pem",
        "ca": "/etc/ssl/certs/lets-encrypt-x3-cross-signed.pem"
    },

    "paymentProcessing": {
        "enabled": true,
        "minConf": 10,
        "paymentMode": "pplnt",
        "_comment_paymentMode": "prop, pplnt",
        "paymentInterval": 120,
        "minimumPayment": 0.1,
        "maxBlocksPerPayment": 1,
        "daemon": {
            "host": "127.0.0.1",
            "port": 3130,
            "user": "*********",
            "password": "*************"
        }
    },

    "ports": {
        "2055": {
            "tls": false,
            "diff": 0.5,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 36,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "poolId": "main",
    "_comment_poolId": "use it for region identification: eu, us, asia or keep default if you have one stratum instance for one coin",

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 3130,
            "user": "**********",
            "password": "****************"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "admin69",
        "database": "anon",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}

**Comment by TheBudda** [comment]
here is my coin file

{
    "name": "anon",
    "symbol": "anon",
    "algorithm": "equihash",
    "parameters": {
        "N": 144,
        "K": 5,
        "personalization": "AnonyPoW"
    },
    "requireShielding": true,
    "peerMagic": "83D847A7",
    "txfee": 0.0004
}

**Comment by TheBudda** [comment]
root@ns3012986:/kush/anon-1.3.0/src# ./anon-cli z_gettotalbalance
{
  "transparent": "15.38",
  "private": "32.45",
  "masternode_collaterals": "0.00",
  "immature_balance": 0.00000000,
  "total": "47.83"
}

**Comment by TheBudda** [comment]
I restarted my dedicated server and restarted ANON and pool
![screenshot 2018-11-10 00 03 46](https://user-images.githubusercontent.com/16983376/48294454-3e791380-e47c-11e8-95d5-7a970f50e4b1.png)

**Comment by TheBudda** [comment]
then I get this error

![screenshot 2018-11-10 00 05 57](https://user-images.githubusercontent.com/16983376/48294497-7d0ece00-e47c-11e8-9b95-5a6b03144553.png)

**Comment by egyptianbman** [comment]
I'm not running anon yet so I don't know if there's anything special with it but in general the coins need to be in the payout address for the pool to be able to process payments.

You can try moving the coins manually to the payout address to get it to process payments. I generally like to keep a buffer in the pool's payout node so that it can process payments without having to wait for shielding the new blocks.
